blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'blogs'

urlpatterns = [
    path('',views.BlogAllList.as_view(), name = 'BlogAllList'),
    path('product_detail/<slug:slug>/', views.product_detail, name='product_detail'),
    path('create/', views.post_create, name='post_create'),
    path('delele/<slug:slug>/',views.delete_post, name='delete_post'),
    path('edit/<slug:slug>', views.edit_post,name="edit_post")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloud_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField(max_length=650)
    country = models.CharField(max_length=50, default='')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='cover/%Y/%m/%d/', blank=True, default='')
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            original_slug = slugify(self.title)
            slug = original_slug
            counter = 1

            
            while Post.objects.filter(slug=slug).exists():
                slug = f"{original_slug}-{counter}"
                counter += 1
            
            self.slug = slug

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content', 'country', 'image']

blog/views.py
from .models import Post
from django.views.generic import ListView
from .forms import PostForm
from django.shortcuts import get_object_or_404, render
from django.shortcuts import render, redirect
from django.urls import reverse
from django.urls import reverse

class BlogAllList(ListView):
    model = Post
    template_name = 'pages/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.all()


def product_detail(request, slug):

    post = get_object_or_404(Post, slug=slug)
    return render(request, 'pages/product_detail.html', {'post': post}) 


def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blogs:BlogAllList')
    else:
        form = PostForm()
    return render(request, 'pages/post_create.html', {'form': form})



def delete_post(request,slug):
    post = get_object_or_404(Post, slug=slug)
    post.delete()
    return redirect('blogs:BlogAllList')


def edit_post(request, slug):
    post = get_object_or_404(Post, slug=slug)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blogs:product_detail', slug=post.slug)
            
    else:
        form = PostForm(instance=post)
            

    return render(request, 'pages/edit_post.html', {'form':form, "post":post})

blog/templates/pages/edit_post.html
{% extends "base.html" %}
{% block content %}
<div class="form_container">
    <h1>Edit Post {{post.title}}</h1>

    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}

        <button  class="btn_delete_detail" type="submit">Save Changes</button>
    </form>
</div>
{% endblock content %}

blog/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title_allpost">All Posts</h1>

    <div class="post_container_main">
        {% for post in posts %}
        <a href="{% url 'blogs:product_detail' post.slug %}">
            <div class="post_container">
                <h4>{{ post.title }}</h4>
                <img src="{{ post.image.url }}" alt="">
                
                <p>
                    {{ post.content|slice:":46" }}{% if post.content|length > 46 %}...{% endif %}
                </p>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock content %}

blog/templates/pages/post_create.html
{% extends "base.html" %}
{% block content %}
<div class="form_container">

    <h1>Create a New Post</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    
</div>
{% endblock content %}

blog/templates/pages/product_detail.html
{% extends "base.html" %}

{% block content %}
<div class="post_container_detail">
    <h1>{{post.title}}</h1>

    <img src="{{post.image.url}}" alt="">

    <p class='post_content_p'>{{post.content}}</p>

    <div class="bottom_detail">
        <p> <strong>From: </strong>{{post.country}}</p>
        <p><strong>Created at:</strong> {{post.created_at}}</p>

        <a href="{% url 'blogs:edit_post' post.slug %}">
            <button class="btn_edit_detail" type="button">Edit post</button>
        </a>

        <form action="{% url 'blogs:delete_post' post.slug %}" method='post'>
            {% csrf_token %}
            <button class="btn_delete_detail" type='submit'>Delete post</button>
        </form>
    </div>
   
 
    
</div>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

    <head>
        {% include 'head.html' %}
        <title>{% block title %}Blog Home{% endblock  %}</title>
    </head>

    <body>

        {% include "templates/header.html" %} 
    <main>
        {% block content %}{% endblock content %}
    </main>
        
    </body>

</html>

templates/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'global/styles.css' %}">

templates/header.html
<header>
  <nav>
    <ul>
      <li>
        <a href="{% url 'blogs:BlogAllList'%}">Home</a>
      </li>
      <li>
        <a href="{% url 'blogs:post_create' %}">New post</a>
      </li>
    </ul>
  </nav>
</header>